# Generated by Django 5.2.7 on 2026-03-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUS_SYSTEM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicleinformation',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
