# Generated by Django 5.2.7 on 2026-02-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUS_SYSTEM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinformation',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehicleinformation',
            name='product_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10),
        ),
    ]
