# Generated by Django 5.2.7 on 2026-03-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUS_SYSTEM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinformation',
            name='stock',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
