# Generated by Django 5.2.7 on 2026-03-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BUS_SYSTEM', '0002_building_is_available_commodity_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleinformation',
            name='available',
        ),
    ]
