# Generated by Django 5.2.7 on 2026-03-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUS_SYSTEM', '0003_vehicleinformation_moto_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinformation',
            name='moto_type',
            field=models.CharField(blank=True, choices=[('cruiser moto', 'Cruiser Moto'), ('sport', 'Sport'), ('dual-sport', 'Dual-Sport'), ('touring moto', 'Touring Moto'), ('off-road moto', 'Off-Road Moto'), ('scooter', 'Scooter'), ('standard moto', 'Standard Moto'), ('other', 'other')], max_length=20, null=True),
        ),
    ]
