# Generated by Django 5.2.7 on 2026-03-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUS_SYSTEM', '0003_remove_vehicleinformation_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinformation',
            name='stock',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
