# Generated by Django 5.2.7 on 2026-03-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUS_SYSTEM', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commodity',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicleinformation',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
