# Generated by Django 5.2.7 on 2026-03-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUS_SYSTEM', '0007_orders_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='property_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Apartment', 'Apartment'), ('Industrial', 'Industrial'), ('Commercial', 'Commercial')], max_length=50),
        ),
    ]
