# Generated by Django 5.2.7 on 2026-03-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUS_SYSTEM', '0008_alter_building_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
