# Generated by Django 5.2.7 on 2026-03-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUS_SYSTEM', '0009_alter_commodity_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleinformation',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
