# Generated by Django 5.2.7 on 2026-03-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUS_SYSTEM', '0010_alter_vehicleinformation_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
