# Generated by Django 5.2.7 on 2026-03-22 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DASHBOARD', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FashionItem',
        ),
    ]
