# Generated by Django 5.2.7 on 2026-04-18 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('CLOTHES', 'Clothing'), ('SHOES', 'Shoes'), ('BAGS', 'Bags'), ('ACCESSORIES', 'Accessories'), ('OTHER', 'Other')], max_length=20)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNISEX', 'Unisex'), ('KIDS', 'Kids')], default='UNISEX', max_length=10)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('size', models.CharField(help_text='e.g., XL, 42, 10-inch', max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('views', models.PositiveIntegerField(default=0, help_text='Number of times this item has been viewed')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fashion_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FashionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fashion/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='fashion/videos/')),
                ('fashion_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='FASHIONITEM.fashionitem')),
            ],
        ),
    ]
