# Generated by Django 5.2.7 on 2026-03-22 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FASHIONITEM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fashion/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='fashion/videos/')),
                ('fashion_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='FASHIONITEM.fashionitem')),
            ],
        ),
    ]
