# Generated by Django 5.2.7 on 2026-03-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FASHIONITEM', '0002_fashionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
