# Generated by Django 5.2.7 on 2026-03-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FASHIONITEM', '0003_fashionitem_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionitem',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this item has been viewed'),
        ),
    ]
