# Generated by Django 5.2.7 on 2026-03-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CART', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='verified',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verification_codes',
        ),
        migrations.AddField(
            model_name='payment',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cart_total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(max_length=50),
        ),
    ]
